name: documakery
version: 0.0.1
description: web client for documakery
dependencies:
  event_bus: any
  route: 
    git: https://github.com/dart-lang/route.git
  unittest: any
  js: any
  browser: any
  web_ui: any
  bootjack:
    git: git://github.com/rikulo/bootjack.git
  logging_handlers: any
