name: documakery
version: 0.0.1
description: web client for documakery
dependencies:
  event_bus: any
  unittest: any
  js: any
  browser: any
  web_ui: any
  widget:
    git: https://github.com/kevmoo/widget.dart.git
