name: doxblox
version: 0.0.1
description: web client for doxblox
dependencies:
  bootjack: any
  event_bus:
    git: https://github.com/marcojakob/dart-event-bus.git
  html5_dnd:
    git: https://github.com/marcojakob/dart-html5-dnd.git
  js: any
  logging_handlers: any
  polymer: any
  route:
    git: https://github.com/dart-lang/route.git
  unittest: any
